### ISSUE TITLE
Cant resolve /.cache/webfonts/webfonts.css after updating to 2.1 / Gatsby 3

### ISSUE THREAD

**Issue by tariknz** [hupe1980/gatsby-plugin-webfonts#22] opened 2021-05-31 08:27 UTC
Hi, starting to get this message for some strange reason. This is on windows.
```
 ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve '/.cache/webfonts/webfonts.css' in
'C:\xx\node_modules\gatsby-plugin-webfonts'

If you're trying to use a package make sure that '/.cache/webfonts/webfonts.css' is installed. If you're trying to   
use a local file make sure that the path is correct.

File: node_modules\gatsby-plugin-webfonts\gatsby-ssr.js:24:39

not finished Building development bundle - 10.767s

npm ERR! code 1
npm ERR! path C:\xx
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c gatsby develop -H 0.0.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\xx\2021-05-31T08_20_30_657Z-debug.log
```

Error seems to be related to webpack but not sure what to do.

Current gatsby deps:
```
    "gatsby": "^3.6.1",
    "gatsby-image": "^3.6.0",
    "gatsby-plugin-material-ui": "^3.0.1",
    "gatsby-plugin-react-helmet": "^4.6.0",
    "gatsby-plugin-sharp": "^3.6.0",
    "gatsby-plugin-sitemap": "^4.2.0",
    "gatsby-plugin-styled-components": "^4.6.0",
    "gatsby-plugin-webfonts": "^2.1.0",
    "gatsby-source-filesystem": "^3.6.0",
    "gatsby-transformer-sharp": "^3.6.0",
```

Not sure if its obvious what's going on but let me know if you need more information.

**Comment by samturner3** [comment] 2021-06-02 01:42
Same here on Mac>

<img width="1289" alt="Screen Shot 2021-06-02 at 11 41 27 am" src="https://user-images.githubusercontent.com/14887388/120411058-7e37db80-c397-11eb-835d-56f7e68a509b.png">
Also on gatsby: 3.6.1

**Comment by adonig** [comment] 2021-06-03 11:41
I got this error because I'm using gatsby-theme-material-ui and pass a webFontsConfig object to prevent Roboto from loading. Interestingly commenting out the config caused the error to go away:

```
  {
    resolve: `gatsby-theme-material-ui`,
    // options: {
    //   webFontsConfig: {
    //     fonts: {}, // Do not load Roboto.
    //   },
    // },
  },
```

**Comment by alec-francis** [comment] 2021-06-19 09:31
Plus 1 to this issue. I'm getting the same error after upgrading our project to Gatsby Version 3

**Comment by robmarshall** [comment] 2021-07-22 09:28
Im getting this, and not using material ui.

**Comment by hupe1980** [comment] 2021-07-22 10:25
Unfortunately, I cannot recreate the failure. The error does not occur locally or in the CI. Can someone create a minimal reproduction?

**Comment by hupe1980** [comment] 2021-07-30 19:36
I close the issue. If it happens again, please create a new issue

**Closed by hupe1980** 2021-07-30 19:36 UTC
